export const ROUTES = {
  HOME: '/',
  SHOP: '/shop',
  PRODUCT: (slug) => `/product/${slug}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: '/order/confirmation',
  ORDERS: '/orders',
  ORDER: (id) => `/orders/${id}`,
  PROFILE: '/profile',
  WISHLIST: '/wishlist',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ADDRESSES: '/addresses',
  FAQ: '/faq',
  SHIPPING: '/shipping',
  RETURNS: '/returns',
  NOT_FOUND: '*',
};
